# clusterPlayers.r -----------------------------------------------------------
# Purpose: 1) Load the PCA artefacts generated by `pcaPlayers.r`
#          2) Inspect what was saved (models, data, labels, feathers)
#          3) (Placeholder) Run clustering on the PCA‑transformed matrices
#          4) Save the resulting clusters for downstream work
#
# NOTE:  Edit `target_year` below to switch seasons. Everything else should
#        “just work” as long as the corresponding RDS / Feather files exist.

library(arrow)   # read_feather()
library(dplyr)   # nice printing / summaries
library(cluster) # for silhouette and other clustering diagnostics
library(FNN)      # fast k‑nearest‑neighbour search

for (year in 2021:2024) {
  # ---- 1. Choose the target season ------------------------------------------
  target_year <- year
  roles <- c("G", "F", "C")

  # ---- 2. Load RDS artefacts -------------------------------------------------
  pca_models <- readRDS(sprintf("Analysis/Clustering/Players/%s/PCA/pca_models.rds", target_year))
  pca_data   <- readRDS(sprintf("Analysis/Clustering/Players/%s/PCA/pca_data.rds",   target_year))
  pca_labels <- readRDS(sprintf("Analysis/Clustering/Players/%s/PCA/pca_labels.rds", target_year))

  set.seed(29)

  library(BasketballAnalyzeR)
  cluster_env <- new.env(hash = TRUE, parent = emptyenv())

  k_roles <- c(G = 69, F = 36, C = 14)

  for (role in roles) {

    k <- k_roles[[role]]
    cluster_env[[role]] <- kclustering(
      data   = pca_data[[role]],
      k      = k,
      labels = paste(pca_labels[[role]]$player_name, pca_labels[[role]]$season_year, sep = " - ")
    )
    chi <- cluster_env[[role]]$Profiles$CHI

    threshold <- 0.8
    clusters_over_threshold <- (cluster_env[[role]]$Profiles %>% filter(CHI > threshold))$ID  
    players_to_reassign <- subset(cluster_env[[role]]$Subjects,
                                  Cluster %in% clusters_over_threshold)

    pca_data[[role]]$player_name_label <- paste(pca_labels[[role]]$player_name, pca_labels[[role]]$season_year, sep = " - ")    
    pca_data[[role]]$season_year <- pca_labels[[role]]$season_year

    players_reassign_merged <- merge(players_to_reassign,
                                    pca_data[[role]],
                                    by.x = "Label",
                                    by.y = "player_name_label")
    
    # --- 1‑NN reassignment ----------------------------------------------------
    # feature columns were already defined in `feats`
    
    # centroids that remain under the CHI threshold
    centroid_df  <- cluster_env[[role]]$Profiles %>% 
                      filter(!ID %in% clusters_over_threshold)  


    feats <- paste0("PC", 1: (ncol(centroid_df) - 2))    
    
    centroid_mat <- as.matrix(centroid_df[ , feats])
    centroid_ids <- centroid_df$ID
    
    # player feature matrix
    player_mat <- as.matrix(players_reassign_merged[ , feats])
    
    # find the single nearest centroid for every player (Euclidean distance)
    nn <- FNN::get.knnx(data  = centroid_mat,
                        query = player_mat,
                        k     = 1)
    
    players_reassign_merged$nearest_cluster <- centroid_ids[nn$nn.index[ , 1]]
    players_reassign_merged$nearest_dist    <- nn$nn.dist[ , 1]

    # ---- Update Subjects table with new cluster assignments -----------------
    subj_idx <- match(players_reassign_merged$Label,
                      cluster_env[[role]]$Subjects$Label)
    cluster_env[[role]]$Subjects$Cluster[subj_idx] <-
      players_reassign_merged$nearest_cluster
    
    # Delete the bad clusters from the profile list so I don't even look at them
    cluster_env[[role]]$Profiles <- cluster_env[[role]]$Profiles %>% filter(!ID %in% clusters_over_threshold)

    # Save profiles, scaling parameters, and labels

    profiles_df <- as.data.frame(cluster_env[[role]]$Profiles)
    print(profiles_df)
    csv_filepath <- sprintf("Analysis/Clustering/Players/%.0f/KClustering/cluster_profiles_%s.csv", year, role)
    write.csv(profiles_df, csv_filepath, row.names = FALSE)

    label_df <- data.frame(
      player_name = pca_labels[[role]]$player_name,
      Cluster     = cluster_env[[role]]$Subjects$Cluster,
      season_year = pca_labels[[role]]$season_year,
      stringsAsFactors = FALSE
    )
    print(head(label_df))
    df_csv_filepath <- sprintf("Analysis/Clustering/Players/%.0f/KClustering/player_labels_%s.csv", year, role)
    write.csv(label_df, df_csv_filepath, row.names = FALSE)
    
  }
  print(paste("Finished year ", target_year))
  
  
}

### DIAGNOSTICS
all_diagnostics <- function() {
# ---- 6. Hybrid Workflow Diagnostics --------------------------------------
  # 1) Gap Statistic
  library(cluster)
  set.seed(1234)
  for (role in roles) {
    cat("\n=== Gap Statistic for Role:", role, "===\n")  
    n_samp <- min(nrow(pca_data[["G"]]), 2000)
    samp_idx <- sample(nrow(pca_data[["G"]]), n_samp)
    gap <- clusGap(
      x      = pca_data[["G"]][samp_idx, ],
      FUN    = kmeans,
      K.max  = 200,
      B      = 10,
      nstart = 10
    )
    quartz()
    plot(gap, main = paste("Gap Statistic – Role:", role))
  }

  # 2) Model-Based Clustering BIC (Gaussian mixtures)
  library(mclust)
  set.seed(1234)
  for (role in roles) {
    cat("\n=== mclust BIC for Role:", role, "===\n")
    m <- Mclust(
      data = pca_data[[role]],
      G    = seq(5, 40)
    )
    quartz()
    plot(m, what = "BIC", main = paste("Mclust BIC – Role:", role))
  }

  # 3) Clustering Stability via Adjusted Rand Index
  library(mclust)  # for adjustedRandIndex
  set.seed(1234)
  for (role in roles) {
    cat("\n=== Stability (ARI) for Role:", role, "===\n")
    data_mat <- pca_data[[role]]
    n <- nrow(data_mat)
    k <- as.integer(n / 50)  # your target clusters
    ari_vals <- replicate(10, {
      km1 <- kmeans(data_mat, centers = k, nstart = 10)
      km2 <- kmeans(data_mat, centers = k, nstart = 10)
      adjustedRandIndex(km1$cluster, km2$cluster)
    })
    cat(sprintf("Mean ARI at k=%d: %.3f  (range: %.3f–%.3f)\n",
                k, mean(ari_vals), min(ari_vals), max(ari_vals)))
  }
  # ---------------------------------------------------------------------------
}

elbow_plot <- function() {
  for (role in roles) {
  cat("\n=== Elbow (WSS) for Role:", role, "===\n")
  role_data <- pca_data[[role]]
  k_max <- 40
  wss <- numeric(k_max)

  for (k in 1:k_max) {
    set.seed(1000 + k)
    km <- kmeans(role_data, centers = k, nstart = 25)
    wss[k] <- km$tot.withinss
    cat("k =", k, "WSS =", as.integer(wss[k]), "\n")
  }

  quartz()
  plot(1:k_max, wss, type = "b", pch = 19,
       xlab = "Number of Clusters (k)",
       ylab = "Total WSS",
       main = paste("Elbow Plot (WSS) – Role:", role))
  }
}

# ---------------------------------------------------------------------------
